### PR TITLE
Fix: Do not visit uninitialized HPyField during traversal.

### LINKED ISSUE #255: test_gc_track fails on debug build of CPython 3.9.2
I am using CPython 3.9.2 built from sources using `../configure --with-pydebug` and I noticed that this test fails:

```
> make && python -m pytest -k test_gc_track -s -v test
...
platform linux -- Python 3.9.2, pytest-6.2.5, py-1.10.0, pluggy-1.0.0 -- <....>
cachedir: .pytest_cache
rootdir: <....>
collected 747 items / 741 deselected / 6 selected                                                                                                                 

test/test_hpyfield.py::TestHPyField::test_gc_track[cpython] ../Modules/gcmodule.c:2162: visit_validate: Assertion failed: PyObject_GC_Track() object is not valid
Enable tracemalloc to get the memory block allocation traceback

object address  : 0x7f395e626780
object refcount : 1
object type     : 0x558c7a375ed0
object type name: mytest.Pair
object repr     : <mytest.Pair object at 0x7f395e626780>

Fatal Python error: _PyObject_AssertFailed: _PyObject_AssertFailed
Python runtime state: initialized
```

(tested on rev 58edcd8)

### PR DESCRIPTION
**Pull request by fangerer**
Should fix #255 .
I'm not sure why we did not copy everything from `Py_VISIT` to `HPy_VISIT` but clearly, `Py_VISIT` will only visit non-null `PyObject *`.
The only drawback now is that we need to do an additional dereference of `hpyfield`.
However, the alternative would be to expose something like `PyObject_GC_Track` in HPy and don't it in `ctx_New`. But I would really not like that.

### CODE REVIEW

File: hpy/devel/include/hpy.h [hunk 1]
```diff
@@ -100,6 +100,7 @@ typedef struct { intptr_t _i; } HPyTracker;
 #define HPy_IsNull(h) ((h)._i == 0)
 
 #define HPyField_NULL ((HPyField){0})
+#define HPyField_IsNull(f) ((f)._i == 0)
```
Comment (fangerer) [inline hpy/devel/include/hpy.h:103]: I would actually not like to expose `HPyField_IsNull`  but since `HPy_VISIT` is public, there are not many options. Anyway, I think it's not a problem since we already expose `HPyField_NULL` and so already implicitly specify that uninitialized `HPyField` has value `0`.

Comment (rlamy) [reply hpy/devel/include/hpy.h:103]: This macro is identical to `HPy_IsNull`, I wonder if we should turn them both into static inline functions to prevent confusions.

**Review by rlamy — APPROVED** [review]
LGTM

File: hpy/devel/include/hpy.h (hunk 1 above)
Comment (fangerer) [reply hpy/devel/include/hpy.h:103]: IIRC we had a comment in an older version of `hpy.c` that also asked this question and since `HPy_FromVoidP` and `HPy_AsVoidP` are also inline functions, it would make sense to me.
Let me merge this PR and I'll open a separate PR to do that. Then we can invite people to discuss that.
