### PR TITLE
Make HPy compatible with Python 3.11

### LINKED ISSUE #288: Unable to compile on Python 3.11 alpha 5
When running `python3.11 -m pip wheel hpy --use-pep517` the output is as follows:

```console
Collecting hpy
  Downloading hpy-0.0.3.tar.gz (172 kB)
     |████████████████████████████████| 172 kB 9.5 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: hpy
  Building wheel for hpy (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/domdf/.local/bin/python3.11 /home/domdf/python311/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmp4xeykvcx
       cwd: /tmp/pip-wheel-9n1000e1/hpy_bf00928872e2496a9d116bd1dd260d92
  Complete output (37 lines):
  fatal: not a git repository (or any of the parent directories): .git
  running bdist_wheel
  running build
  running build_py
  running egg_info
  writing hpy.egg-info/PKG-INFO
  writing dependency_links to hpy.egg-info/dependency_links.txt
  writing entry points to hpy.egg-info/entry_points.txt
  writing requirements to hpy.egg-info/requires.txt
  writing top-level names to hpy.egg-info/top_level.txt
  listing git files failed - pretending there aren't any
  reading manifest file 'hpy.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  adding license file 'LICENSE'
  running build_ext
  building 'hpy.universal' extension
  hpy/debug/src/debug_ctx_cpython.c: In function ‘debug_ctx_CallRealFunctionFromTrampoline’:
  hpy/debug/src/debug_ctx_cpython.c:162:20: error: dereferencing pointer to incomplete type ‘cpy_Py_buffer’ {aka ‘struct bufferinfo’}
    162 |             a->view->obj = NULL;
        |                    ^~
  hpy/debug/src/debug_ctx_cpython.c:165:36: warning: passing argument 3 of ‘_buffer_h2py’ from incompatible pointer type [-Wincompatible-pointer-types]
    165 |         _buffer_h2py(dctx, &hbuf, a->view);
        |                                   ~^~~~~~
        |                                    |
        |                                    cpy_Py_buffer * {aka struct bufferinfo *}
  hpy/debug/src/debug_ctx_cpython.c:41:78: note: expected ‘Py_buffer *’ {aka ‘struct <anonymous> *’} but argument is of type ‘cpy_Py_buffer *’ {aka ‘struct bufferinfo *’}
     41 | static void _buffer_h2py(HPyContext *dctx, const HPy_buffer *src, Py_buffer *dest)
        |                                                                   ~~~~~~~~~~~^~~~
  hpy/debug/src/debug_ctx_cpython.c:173:29: warning: passing argument 2 of ‘_buffer_py2h’ from incompatible pointer type [-Wincompatible-pointer-types]
    173 |         _buffer_py2h(dctx, a->view, &hbuf);
        |                            ~^~~~~~
        |                             |
        |                             cpy_Py_buffer * {aka struct bufferinfo *}
  hpy/debug/src/debug_ctx_cpython.c:56:61: note: expected ‘const Py_buffer *’ {aka ‘const struct <anonymous> *’} but argument is of type ‘cpy_Py_buffer *’ {aka ‘struct bufferinfo *’}
     56 | static void _buffer_py2h(HPyContext *dctx, const Py_buffer *src, HPy_buffer *dest)
        |                                            ~~~~~~~~~~~~~~~~~^~~
  error: command '/usr/bin/gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for hpy
Failed to build hpy
ERROR: Failed to build one or more wheels

```

The output is more or less the same when building from git, with some of the line numbers changing.

-----

It looks like `bufferinfo` was removed in https://github.com/python/cpython/pull/29991, which made it into alpha 5.

It's used here:

https://github.com/hpyproject/hpy/blob/dd702f55ce391df43cbf5dab1ce7d4b1be23110b/hpy/devel/include/hpy/cpy_types.h#L12

### PR DESCRIPTION
**Pull request by fangerer**
This resolves #288 .

Antonio's Hybrid-ABI PR #371, which is now merged, already solved the first problems we had with Python 3.11. However, that was not enough.
In particular, there was a subtle change in Python's `PyType_FromSpec....` They do now copy the name from the type spec into a fresh buffer such that the type object owns that buffer and can free it (see https://github.com/python/cpython/blob/b5b3904f05e77f044f158307bc6bdd2bc1b670a2/Objects/typeobject.c#L3723).
However, we use `tp_name` to attach our `HPyType_Extra` struct.

In future, we might consider to use meta classes to avoid this hack.

I've now also added Python 3.11 to the CI (for main tests and PoC).

### CODE REVIEW

File: hpy/devel/src/runtime/ctx_type.c [hunk 1]
```diff
@@ -1130,6 +1136,18 @@ ctx_Type_FromSpec(HPyContext *ctx, HPyType_Spec *hpyspec,
...
+    /* Since Python 3.11, the name will be copied into a fresh buffer such that
+       the type objects owns this buffer. Hence we need to patch the pointer
+       again. The nice thing is that Python will then free out HPyType_Extra
+       for us. The internal field '_ht_tpname' is only used for freeing. So, we
+       can set it to 'extra'. */
+    PyHeapTypeObject *ht = (PyHeapTypeObject *) result;
+    PyMem_Free(ht->_ht_tpname);
+    ht->_ht_tpname = (char *) extra;
+    ht->ht_type.tp_name = (const char *)extra->name;
+#endif
```
Comment (antocuni) [inline hpy/devel/src/runtime/ctx_type.c:1149]: wow, this is brilliant.
It's also a bit scary, because if someone by chance tries to access _ht_tpname you will get nonsense. But it seems that nobody is accessing it anyway, so I suppose it's fine :+1:

**Review by antocuni — APPROVED** [review]
LGTM

File: hpy/devel/src/runtime/ctx_type.c (hunk 1 above)
Comment (fangerer) [reply hpy/devel/src/runtime/ctx_type.c:1149]: I agree. I checked the CPython code and it's really just used for freeing.
As I mentioned, we could maybe use a metaclass for HPy types to store the extra info. I'll investigate.
